spring:
  config:
    activate:
      on-profile: local

## redis
  redis:
    host: localhost
    port: 6379
    password: 1234

## mysql
  application:
    name: hhplus_ecommerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/hhecommerce?serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false


## h2
#    datasource:
#        driverClassName: org.h2.Driver
#        url: jdbc:h2:mem:testdb:~/h2db
#        username: sa
#        password:
#        url: jdbc:h2:mem:testdb:tcp://localhost/~/h2db
#        url: jdbc:h2:mem:testdb:~/h2db;AUTO_SERVER=true

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#      enabled: 'true'